package org.kevin.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.kevin.dao.model.Answer;
import org.kevin.dao.model.AnswerExample;

public interface AnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    long countByExample(AnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    int deleteByExample(AnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    int insert(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    int insertSelective(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    List<Answer> selectByExampleWithBLOBs(AnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    List<Answer> selectByExample(AnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    Answer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") Answer record, @Param("example") AnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Answer record, @Param("example") AnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    int updateByExample(@Param("record") Answer record, @Param("example") AnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    int updateByPrimaryKeySelective(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    int updateByPrimaryKey(Answer record);
}