package org.kevin.dao.model;

public class Answer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.id
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.answerer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    private String answerer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer.content
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.id
     *
     * @return the value of answer.id
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.id
     *
     * @param id the value for answer.id
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.answerer
     *
     * @return the value of answer.answerer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public String getAnswerer() {
        return answerer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.answerer
     *
     * @param answerer the value for answer.answerer
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public void setAnswerer(String answerer) {
        this.answerer = answerer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer.content
     *
     * @return the value of answer.content
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer.content
     *
     * @param content the value for answer.content
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}