package org.kevin.dao.model;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.user_id
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.favorite_times
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    private Integer favoriteTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.description
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.user_id
     *
     * @return the value of question.user_id
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.user_id
     *
     * @param userId the value for question.user_id
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.favorite_times
     *
     * @return the value of question.favorite_times
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public Integer getFavoriteTimes() {
        return favoriteTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.favorite_times
     *
     * @param favoriteTimes the value for question.favorite_times
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public void setFavoriteTimes(Integer favoriteTimes) {
        this.favoriteTimes = favoriteTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.description
     *
     * @return the value of question.description
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.description
     *
     * @param description the value for question.description
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }
}