package org.kevin.dao.model;

public class Topic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.name
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.status
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.name
     *
     * @return the value of topic.name
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.name
     *
     * @param name the value for topic.name
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.status
     *
     * @return the value of topic.status
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.status
     *
     * @param status the value for topic.status
     *
     * @mbg.generated Mon Nov 27 14:29:32 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}